package com.gaka.service;

import org.springframework.ai.document.Document;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Service;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Service
public class CsvIngestorService implements CommandLineRunner {

    private final VectorStore vectorStore;
    
    @Value("${gaka.csv.path:../gaka_feature_mapping.csv}")
    private String csvPath;

    public CsvIngestorService(VectorStore vectorStore) {
        this.vectorStore = vectorStore;
    }

    @Override
    public void run(String... args) throws Exception {
        System.out.println("Starting CSV Ingestion from: " + csvPath);
        
        List<Document> documents = new ArrayList<>();
        
        try (BufferedReader br = new BufferedReader(new FileReader(csvPath))) {
            String line;
            boolean firstLine = true;
            while ((line = br.readLine()) != null) {
                if (firstLine) {
                    firstLine = false;
                    continue; // Skip header
                }
                
                // Simple CSV parsing (assuming no commas in fields for MVP, or handle better)
                // Using regex to handle quoted fields if generated by script
                String[] parts = line.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)", -1);
                
                if (parts.length >= 6) {
                    String id = clean(parts[0]);
                    String name = clean(parts[1]);
                    String desc = clean(parts[2]);
                    String url = clean(parts[3]);
                    String utterances = clean(parts[4]);
                    String platform = clean(parts[5]);

                    String content = "Feature: " + name + ". Description: " + desc + ". Utterances: " + utterances;
                    
                    Document doc = new Document(content, Map.of(
                        "id", id,
                        "url_path", url,
                        "platform", platform,
                        "name", name
                    ));
                    documents.add(doc);
                }
            }
        } catch (Exception e) {
            System.err.println("Error reading CSV: " + e.getMessage());
            return;
        }

        if (!documents.isEmpty()) {
            // For MVP, simplistic add. In prod, check existing or upsert.
            System.out.println("Adding " + documents.size() + " documents to Vector Store...");
            vectorStore.add(documents);
            System.out.println("Ingestion Complete.");
        } else {
            System.out.println("No documents found to ingest.");
        }
    }
    
    private String clean(String input) {
        if (input != null && input.startsWith("\"") && input.endsWith("\"")) {
            return input.substring(1, input.length() - 1);
        }
        return input;
    }
}
